pipeline {
  agent {
    docker {
      image 'amioranza/kubectl:1.17'
      args '-v /var/jenkins_home/.kube:/root/.kube'
    }
  }
  
  parameters {
    string(name: 'REPO', defaultValue: 'amioranza', description: '')
    string(name: 'APP', defaultValue: '', description: '')
    string(name: 'TAG', defaultValue: '', description: '')
  }

  stages {

    stage('Checkout') {
      steps{
        checkout scm
      }
    }

    stage('Package and Push') {
      steps{
        sh "ls -l"
        sh "cp deploy/Dockerfile ."
        sh "sed -i 's/__JAR__/${env.APP}/g' Dockerfile"
        // sh "docker build -t ${REPO}/${env.APP}:${env.TAG} ."
        script{
          docker.withRegistry('https://index.docker.io/v1/', 'dockerhub') {
            def app = docker.build("${REPO}/${APP}:${TAG}", '.')
            app.push()
            app.push('latest')
          }
        }
      }
    }

    stage('Deploy'){
      steps{
        sh 'kubectl --kubeconfig /var/jenkins_home/.kube/config version'
      }
    }

  }
}