# -*- mode: ruby -*-
# vi: set ft=ruby :


VAGRANTFILE_API_VERSION = "2"

cluster = {
  "tt" => { :name => "tt", :ip1 => "192.168.157.100", :ip2 => "192.168.197.100", :cpus => 2, :mem => 4096, :script => "deploy.sh"}
}


Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  cluster.each_with_index do |(hostname, info), index|
  
    config.hostmanager.enabled = true
  
    config.vm.define hostname do |cfg|
      cfg.vm.provider :virtualbox do |vb, override|
        vb.default_nic_type = "82543GC"
        config.vm.box = "ubuntu/bionic64"
        config.vm.synced_folder ".", "/vagrant"
        if hostname == 'tt'
          override.vm.network "forwarded_port", guest: 80, host: 8080
          override.vm.network "forwarded_port", guest: 443, host: 8443
        end
        override.vm.network :private_network, ip: "#{info[:ip1]}", nic_type: "virtio"
        override.vm.network :private_network, ip: "#{info[:ip2]}", nic_type: "virtio"
        override.vm.hostname = hostname
        vb.name = hostname
        vb.customize ["modifyvm", :id, "--memory", info[:mem], "--cpus", info[:cpus], "--hwvirtex", "on"]
      end # end provider
      cfg.vm.provision :shell, path: info[:script], keep_color: "true"
    end # end config
  end # end cluster
end
